module.exports = {
  content: ['./src/**/*.{ts,tsx,js,jsx}', './public/**/*.html'],
  theme: {
    extend: {
      spacing: {
        'dock-w': '300px',
        'tools-w': '54px',
        'menu-h': '24px',
        'options-h': '34px',
        'tab-h': '20px',
        'panel-header': '22px',
      },
      minWidth: {
        'app': '980px',
      },
      width: {
        'dock-w': '300px',
        'tools-w': '54px',
      },
      height: {
        'menu': '24px',
        'options': '34px',
        'tab': '20px',
      },
      colors: {
        'background': 'hsl(var(--background))',
        'foreground': 'hsl(var(--foreground))',
        'panel': 'hsl(var(--panel))',
        'panel-foreground': 'hsl(var(--panel-foreground))',
        'panel-header': 'hsl(var(--panel-header))',
        'border': 'hsl(var(--border))',
        'border-light': 'hsl(var(--border-light))',
        'border-dark': 'hsl(var(--border-dark))',
        'input': 'hsl(var(--input))',
        'muted': 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        'accent': 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        'workspace': 'hsl(var(--workspace))',
        'workspace-foreground': 'hsl(var(--workspace-foreground))',
        'document': 'hsl(var(--document))',
        'document-foreground': 'hsl(var(--document-foreground))',
        'document-shadow': 'hsl(var(--document-shadow))',
        'ruler': 'hsl(var(--ruler))',
        'ruler-foreground': 'hsl(var(--ruler-foreground))',
        'ruler-tick': 'hsl(var(--ruler-tick))',
        'ruler-cursor': 'hsl(var(--ruler-cursor))',
        'highlight': 'hsl(var(--highlight))',
        'shadow': 'hsl(var(--shadow))',
        'tool-active': 'hsl(var(--tool-active))',
        'tool-hover': 'hsl(var(--tool-hover))',
        'layer-selected': 'hsl(var(--layer-selected))',
        'layer-selected-foreground': 'hsl(var(--layer-selected-foreground))',
        'menu-hover': 'hsl(var(--menu-hover))',
        'menu-hover-foreground': 'hsl(var(--menu-hover-foreground))',
        'tab-bar': 'hsl(var(--tab-bar))',
        'tab-active': 'hsl(var(--tab-active))',
        'tab-inactive': 'hsl(var(--tab-inactive))',
        'swatch-background': 'hsl(var(--swatch-background))',
        'swatch-foreground': 'hsl(var(--swatch-foreground))',
        'checker': '#888888',
      },
    },
  },
  plugins: [],
};
